### ISSUE TITLE
Ignore GREASE in EC

### ISSUE THREAD

**Issue by bartebor** [fooinha/nginx-ssl-ja3#14]
GREASE in EC algorithms (supported_groups) is not ignored:

```
[...]
2019/05/28 09:35:23 [debug] 3065#0: *3 ssl_ja3: curves: length: 4

2019/05/28 09:35:23 [debug] 3065#0: *3 ssl_ja3: |    curves: 23130
2019/05/28 09:35:23 [debug] 3065#0: *3 ssl_ja3: |    curves: 29
2019/05/28 09:35:23 [debug] 3065#0: *3 ssl_ja3: |    curves: 23
2019/05/28 09:35:23 [debug] 3065#0: *3 ssl_ja3: |    curves: 24
[...]
2019/05/28 09:35:23 [debug] 3065#0: *3 ssl_ja3: fp: [771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-10,23-65281-10-11-35-16-5-13-18-51-45-43-27-21,23130-29-23-24,0]
```
EC fragment `23130-29-23-24` contains GREASE (`0x5A5A`), what makes JA3 a little bit random - JA3 should be `771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-10,23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0` instead.

It is very easy to fix, I can create a PR.

**Comment by Sessa93** [comment]
@bartebor Nice, please open the PR!

**Comment by Sessa93** [comment]
Also if you want to check the correctness of the fingerprint, use this: https://ja3er.com/

**Comment by bartebor** [comment]
I tried to compare results using website provided, but it seems it ignores EC:
```
# nginx
771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-10,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,29-23-24,0
# ja3er.com
771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-10,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-21,,
```
I confirmed that EC extensions are present in both cases (they are visible in JA3 extensions field and in wireshark):
```
Extension: supported_groups (len=10)
    Type: supported_groups (10)
    Length: 10
    Supported Groups List Length: 8
    Supported Groups (4 groups)
        Supported Group: Reserved (GREASE) (0xcaca)
        Supported Group: x25519 (0x001d)
        Supported Group: secp256r1 (0x0017)
        Supported Group: secp384r1 (0x0018)
Extension: ec_point_formats (len=2)
    Type: ec_point_formats (11)
    Length: 2
    EC point formats Length: 1
    Elliptic curves point formats (1)
        EC point format: uncompressed (0)
```

**Comment by Sessa93** [comment]
It may be reasonable, Chrome may respond with different fingerprints depending on the specific situation. 
If you switch between incognito and normal mode sometimes the fingerprint changes.

**Comment by fooinha** [comment]
Please check if with new version in master after #12 merge rewrite, that this still happens.
