### ISSUE TITLE
Add modern nginx / openssl3 patches

### ISSUE THREAD

**Issue by sp3nx0r** [fooinha/nginx-ssl-ja3#40]
Patches don't successfully apply on a fresh ubuntu:jammy openresty installation, no surprise. Need to add patch files for these modern versions.

**Comment by fooinha** [comment]
Please try, again, patches were updated for stable version of openssl 1.1.1

**Comment by zentavr** [comment]
@fooinha - Ubuntu 22.04 comes with OpenSSL 3.0.2-0ubuntu1.6, not 1.1.1

**Comment by fooinha** [comment]
@zentavr , I'll take a look as soon as I find some time. Thanx

**Comment by fooinha** [comment]
@zentavr, I've used the following version for openssl.

```
  6 [remote "origin"]
  7     url = https://github.com/openssl/openssl
  8     fetch = +refs/tags/openssl-3.0.5:refs/tags/openssl-3.0.5
```

I patched it, compiled it, and used for compilation of nginx and this module, and the patches are compatible.

So, the current patches for OpenSSL can also be used for the newer 3.0.x versions.

**Comment by zentavr** [comment]
Hello @fooinha - the stupid question:
How can I specify which OpenSSL folder with sources to use while compiling nginx?

In the readme there is nothing about this:

```shell
# Configure

$ ./configure --add-module=/build/ngx_ssl_ja3 --with-http_ssl_module --with-stream_ssl_module --with-debug --with-stream
```

**Comment by zentavr** [comment]
Seems like I do need to set `--with-openssl=` flag while doing `./configure`
