### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by David-Hang-12138** [fooinha/nginx-ssl-ja3#42]
I installed the latest version of openssl
`$ openssl version
OpenSSL 1.1.1q  5 Jul 2022
`
But when I try to build dynamic module with nginx-ssl-ja3, it fails with the following error.
`adding module in ../nginx-ssl-ja3/
 + ngx_ssl_ja3: stream support
checking for SSL_CTX_set_client_hello_cb() ... not found
 ! incorrect OpenSSL version. use >= 1.1.1
`
Can anybody help me solving this issue?
I did all the instructions in the following link, patched all.
https://www.bbmax.cc/index.php/archives/80/
What did I miss?
Thank you.

**Comment by fooinha** [comment]
we would need to check if this module is compatible with 1.1.1q

**Comment by David-Hang-12138** [comment]
Thanks for quick reply.
Which version of openssl should I use? Should I use openssl 1.1.1?

**Comment by David-Hang-12138** [comment]
I reinstalled openssl 1.1.1, but still fails with same error

configuring additional dynamic modules
adding module in ../nginx-ssl-ja3
 + ngx_ssl_ja3: stream support
checking for SSL_CTX_set_client_hello_cb() ... not found
 ! incorrect OpenSSL version. use >= 1.1.1
[user@centos nginx-1.22.0]$ openssl version
OpenSSL 1.1.1  11 Sep 2018
[user@centos nginx-1.22.0]$

**Comment by fooinha** [comment]
This should be fixed with #43
