### ISSUE TITLE
Support OpenSSL 3

### ISSUE THREAD

**Issue by cello86** [fooinha/nginx-ssl-ja3#50]
Hi All,
could you confirm is this module is supported by OpenSSL 3.x?

Thanks,
Marcello

**Comment by Binary-Vanguard-12138** [comment]
OpenSSL 1.1.1 reached the end of life in 2023 according to this [link](https://openssl-library.org/post/2023-03-28-1.1.1-eol/).
So it would be great if some one could support OpenSSL 3.

**Comment by fooinha** [comment]
Maybe I could try to add support to this. I'll take a look.

**Comment by fooinha** [comment]
Added patches for OpenSSL 3 .
Are very similar to OpenSSL 1.1.1 .
